/**
 * Next.js configuration generated by HexDDD-VibePDK merger.
 * Use this file to override framework defaults when needed.
 */

const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  eslint: {
    ignoreDuringBuilds: true,
  },
  experimental: {
    instrumentationHook: false,
  },
};

module.exports = nextConfig;
