/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Feature {
  /**
   * The name of the feature
   */
  name: string;
  /**
   * The name of the domain to create the feature in.
   */
  domain: string;
  /**
   * A directory where the feature will be created.
   */
  directory?: string;
}
